#!/bin/bash
emcc perlin.c -o perlin-wasm.html \
-s EXPORTED_FUNCTIONS='["_generatePerlinNoise"]' \
-s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' \
-s WASM=1

#echo "export default Module;" >> perlin-wasm.js
